### ISSUE TITLE
Class Icons: use CSS instead of images and add support for high-DPI displays (retina/4k/high-res screens)

### ISSUE THREAD

**Issue by mschnee** [FFXIVCrafting/ffxivcrafting#134]
*Issue*
The icons used on caas are single-images, and look blocky on retina displays because they aren't taking advantage of device pixel ration media queries.

*Action items:*
- [ ] Create two spritesheets, one with the 24px icons, one with 48px icons (2x size)

- [ ] Replace the image tags with inline tags that are styled with a spritesheet.
```html
<img src="/img/classes/CRP.png" rel="tooltip" title="" data-original-title="Carpenter">
```
with
```html
<i class="class-icon CRP" rel="tooltip" title="" data-original-title="Carpenter" />
```

- [ ] and add the following CSS
```css
i.class-icon {
    display: inline-block;
    overflow: hidden;
    width: 24px;
    height: 24px;
    background-image: url("path/to/disciples-of-hand-24.png");
    background-repeat: no-repeat;
    background-size: 24px height-px; // Do not override this in the high-dpi class, these dimensions are used by the highdpi browser to determine how to scale the image- the high dpi image will be twice the size, webkit will see this line, and the math computes to a scale of 1.0 instead of 2.0.
}
.class-icon.CRP {
    background-position: 0 0;
}
```

- [ ] Add the following for high-dpi (retina display) support css
```css
@media only screen and (-Webkit-min-device-pixel-ratio: 1.5),
only screen and (-moz-min-device-pixel-ratio: 1.5),
only screen and (-o-min-device-pixel-ratio: 3/2),
only screen and (min-device-pixel-ratio: 1.5) {
        i.class-icons: {
            background-image: url("disciples-of-hand-48.png");
        }
    }
```

- [ ] Create individual offset classes for all the class/job sprites, using the dimensions of the 1x (low-dpi) spritesheet.

*Why don't you do it yourself and create a pull request?*
I'm on an iPad flying across the country right now.  I'd be happy to do this when I get home.
